name: Build HTVP

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch: 
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'
      - '.gitignore'

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout Builds Branch
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: "builds"
          path: "builds"
          
      - name: Initialize Builds Branch (If Missing)
        run: |
          if [ ! -d "builds/.git" ]; then
            echo "Builds branch missing. Initializing new orphan branch..."
            mkdir -p builds
            cd builds
            git init
            git checkout --orphan builds
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            echo "Init" > dummy.txt
            git add dummy.txt
            git commit -m "Initialize builds branch"
          fi

      - name: Clean Old Builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup Fast JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK Environment
        uses: android-actions/setup-android@v3

      - name: Compile HTVP Plugin
        run: |
          cd $GITHUB_WORKSPACE/src
          sed -i -e 's/\r$//' gradlew
          chmod +x gradlew
          ./gradlew make makePluginsJson
          find . -type f -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds/ \;
          cp build/plugins.json $GITHUB_WORKSPACE/builds/ || true

      - name: Push Release to Repository
        run: |
          # Copy files to the workspace root instead of a 'builds' folder
          cp -f **/build/*.cs3 $GITHUB_WORKSPACE/
          cp -f build/plugins.json $GITHUB_WORKSPACE/
          
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # Add and commit to the main branch
          git add HTVP.cs3 plugins.json
          git commit -m "Deploy HTVP Build $GITHUB_SHA" || exit 0
          git push origin main
